# Generated by Django 2.2.20 on 2021-07-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comedians_jokes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedians',
            name='joke_id',
        ),
    ]
